-- GreenMarket schema only
-- Generated by splitting oldgreenmarket.sql

-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 14, 2026 at 11:59 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database schema for GreenMarket / oldgreenmarket
--

-- --------------------------------------------------------

--
-- Table structure for table `avis`
--

CREATE TABLE `avis` (
  `ID_Avis` int(11) NOT NULL,
  `note` int(11) NOT NULL,
  `commentaire` text DEFAULT NULL,
  `ID_utili` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ;

-- --------------------------------------------------------

--
-- Table structure for table `boutique`
--

CREATE TABLE `boutique` (
  `ID_boutique` int(11) NOT NULL,
  `nom_boutique` varchar(150) NOT NULL,
  `description_boutique` text DEFAULT NULL,
  `ville` varchar(100) DEFAULT NULL,
  `ID_utili` int(11) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `categorie`
--

CREATE TABLE `categorie` (
  `ID_Categ` int(11) NOT NULL,
  `nom_Categ` varchar(100) NOT NULL,
  `description_Categ` text DEFAULT NULL,
  `Categ_img` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `commande`
--

CREATE TABLE `commande` (
  `ID_Com` int(11) NOT NULL,
  `date_com` datetime DEFAULT current_timestamp(),
  `status_com` varchar(50) NOT NULL DEFAULT 'en attente',
  `prix_total` decimal(10,2) NOT NULL,
  `ID_utili` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `favoris`
--

CREATE TABLE `favoris` (
  `ID_utili` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `ligne_commande`
--

CREATE TABLE `ligne_commande` (
  `ID_Com` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `Quantite` int(11) NOT NULL,
  `Prix_Unitaire` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `ligne_panier`
--

CREATE TABLE `ligne_panier` (
  `ID_Panier` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `Quantite` int(11) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notification`
--

CREATE TABLE `notification` (
  `ID_Noti` int(11) NOT NULL,
  `message` text NOT NULL,
  `est_lu` tinyint(1) DEFAULT 0,
  `ID_utili` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `paiement`
--

CREATE TABLE `paiement` (
  `ID_Pay` int(11) NOT NULL,
  `mode_pay` varchar(50) NOT NULL,
  `montant` decimal(10,2) NOT NULL,
  `date_pay` datetime DEFAULT current_timestamp(),
  `ID_Com` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `panier`
--

CREATE TABLE `panier` (
  `ID_Panier` int(11) NOT NULL,
  `ID_utili` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `produit`
--

CREATE TABLE `produit` (
  `ID_Prod` int(11) NOT NULL,
  `nom_Prod` varchar(150) NOT NULL,
  `Prix` decimal(10,2) NOT NULL,
  `Stock` int(11) NOT NULL DEFAULT 0,
  `Prod_img` varchar(255) DEFAULT NULL,
  `ID_boutique` int(11) NOT NULL,
  `ID_Categ` int(11) NOT NULL,
  `description` text DEFAULT NULL,
  `est_active` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `produit_caracteristique`
--

CREATE TABLE `produit_caracteristique` (
  `ID_Caract` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `texte` varchar(255) NOT NULL,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `produit_image`
--

CREATE TABLE `produit_image` (
  `ID_Image` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `image_path` varchar(255) NOT NULL,
  `is_main` tinyint(1) DEFAULT 0,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `produit_option`
--

CREATE TABLE `produit_option` (
  `ID_Option` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `label` varchar(100) NOT NULL,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `produit_option_valeur`
--

CREATE TABLE `produit_option_valeur` (
  `ID_Valeur` int(11) NOT NULL,
  `ID_Option` int(11) NOT NULL,
  `valeur` varchar(100) NOT NULL,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `reclamation`
--

CREATE TABLE `reclamation` (
  `ID_Reclam` int(11) NOT NULL,
  `description` text NOT NULL,
  `status_reclam` varchar(50) DEFAULT 'ouverte',
  `ID_Com` int(11) NOT NULL,
  `ID_utili` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `reponse`
--

CREATE TABLE `reponse` (
  `ID_Rep` int(11) NOT NULL,
  `message` text NOT NULL,
  `ID_utili` int(11) NOT NULL,
  `ID_Avis` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `traceabilite`
--

CREATE TABLE `traceabilite` (
  `ID_Trace` int(11) NOT NULL,
  `ID_Prod` int(11) NOT NULL,
  `titre` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `lieu` varchar(150) DEFAULT NULL,
  `date_trace` varchar(50) DEFAULT NULL,
  `icone` varchar(50) DEFAULT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `utilisateur`
--

CREATE TABLE `utilisateur` (
  `ID_utili` int(11) NOT NULL,
  `nom` varchar(100) NOT NULL,
  `prenom` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `mot_de_passe` varchar(255) NOT NULL,
  `role` varchar(20) NOT NULL DEFAULT 'client',
  `telephone` varchar(30) DEFAULT NULL,
  `adresse` varchar(255) DEFAULT NULL,
  `est_active` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `avis`
--
ALTER TABLE `avis`
  ADD PRIMARY KEY (`ID_Avis`),
  ADD KEY `ID_utili` (`ID_utili`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `boutique`
--
ALTER TABLE `boutique`
  ADD PRIMARY KEY (`ID_boutique`),
  ADD KEY `ID_utili` (`ID_utili`);

--
-- Indexes for table `categorie`
--
ALTER TABLE `categorie`
  ADD PRIMARY KEY (`ID_Categ`);

--
-- Indexes for table `commande`
--
ALTER TABLE `commande`
  ADD PRIMARY KEY (`ID_Com`),
  ADD KEY `ID_utili` (`ID_utili`);

--
-- Indexes for table `favoris`
--
ALTER TABLE `favoris`
  ADD PRIMARY KEY (`ID_utili`,`ID_Prod`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `ligne_commande`
--
ALTER TABLE `ligne_commande`
  ADD PRIMARY KEY (`ID_Com`,`ID_Prod`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `ligne_panier`
--
ALTER TABLE `ligne_panier`
  ADD PRIMARY KEY (`ID_Panier`,`ID_Prod`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `notification`
--
ALTER TABLE `notification`
  ADD PRIMARY KEY (`ID_Noti`),
  ADD KEY `ID_utili` (`ID_utili`);

--
-- Indexes for table `paiement`
--
ALTER TABLE `paiement`
  ADD PRIMARY KEY (`ID_Pay`),
  ADD KEY `ID_Com` (`ID_Com`);

--
-- Indexes for table `panier`
--
ALTER TABLE `panier`
  ADD PRIMARY KEY (`ID_Panier`),
  ADD KEY `ID_utili` (`ID_utili`);

--
-- Indexes for table `produit`
--
ALTER TABLE `produit`
  ADD PRIMARY KEY (`ID_Prod`),
  ADD KEY `ID_boutique` (`ID_boutique`),
  ADD KEY `ID_Categ` (`ID_Categ`);

--
-- Indexes for table `produit_caracteristique`
--
ALTER TABLE `produit_caracteristique`
  ADD PRIMARY KEY (`ID_Caract`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `produit_image`
--
ALTER TABLE `produit_image`
  ADD PRIMARY KEY (`ID_Image`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `produit_option`
--
ALTER TABLE `produit_option`
  ADD PRIMARY KEY (`ID_Option`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `produit_option_valeur`
--
ALTER TABLE `produit_option_valeur`
  ADD PRIMARY KEY (`ID_Valeur`),
  ADD KEY `ID_Option` (`ID_Option`);

--
-- Indexes for table `reclamation`
--
ALTER TABLE `reclamation`
  ADD PRIMARY KEY (`ID_Reclam`),
  ADD KEY `ID_Com` (`ID_Com`),
  ADD KEY `ID_utili` (`ID_utili`);

--
-- Indexes for table `reponse`
--
ALTER TABLE `reponse`
  ADD PRIMARY KEY (`ID_Rep`),
  ADD KEY `ID_utili` (`ID_utili`),
  ADD KEY `ID_Avis` (`ID_Avis`);

--
-- Indexes for table `traceabilite`
--
ALTER TABLE `traceabilite`
  ADD PRIMARY KEY (`ID_Trace`),
  ADD KEY `ID_Prod` (`ID_Prod`);

--
-- Indexes for table `utilisateur`
--
ALTER TABLE `utilisateur`
  ADD PRIMARY KEY (`ID_utili`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `avis`
--
ALTER TABLE `avis`
  MODIFY `ID_Avis` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `boutique`
--
ALTER TABLE `boutique`
  MODIFY `ID_boutique` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `categorie`
--
ALTER TABLE `categorie`
  MODIFY `ID_Categ` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `commande`
--
ALTER TABLE `commande`
  MODIFY `ID_Com` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `notification`
--
ALTER TABLE `notification`
  MODIFY `ID_Noti` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `paiement`
--
ALTER TABLE `paiement`
  MODIFY `ID_Pay` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `panier`
--
ALTER TABLE `panier`
  MODIFY `ID_Panier` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `produit`
--
ALTER TABLE `produit`
  MODIFY `ID_Prod` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `produit_caracteristique`
--
ALTER TABLE `produit_caracteristique`
  MODIFY `ID_Caract` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT for table `produit_image`
--
ALTER TABLE `produit_image`
  MODIFY `ID_Image` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- AUTO_INCREMENT for table `produit_option`
--
ALTER TABLE `produit_option`
  MODIFY `ID_Option` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `produit_option_valeur`
--
ALTER TABLE `produit_option_valeur`
  MODIFY `ID_Valeur` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;

--
-- AUTO_INCREMENT for table `reclamation`
--
ALTER TABLE `reclamation`
  MODIFY `ID_Reclam` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `reponse`
--
ALTER TABLE `reponse`
  MODIFY `ID_Rep` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `traceabilite`
--
ALTER TABLE `traceabilite`
  MODIFY `ID_Trace` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `utilisateur`
--
ALTER TABLE `utilisateur`
  MODIFY `ID_utili` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `avis`
--
ALTER TABLE `avis`
  ADD CONSTRAINT `avis_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`),
  ADD CONSTRAINT `avis_ibfk_2` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`);

--
-- Constraints for table `boutique`
--
ALTER TABLE `boutique`
  ADD CONSTRAINT `boutique_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`);

--
-- Constraints for table `commande`
--
ALTER TABLE `commande`
  ADD CONSTRAINT `commande_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`);

--
-- Constraints for table `favoris`
--
ALTER TABLE `favoris`
  ADD CONSTRAINT `favoris_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`),
  ADD CONSTRAINT `favoris_ibfk_2` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`);

--
-- Constraints for table `ligne_commande`
--
ALTER TABLE `ligne_commande`
  ADD CONSTRAINT `ligne_commande_ibfk_1` FOREIGN KEY (`ID_Com`) REFERENCES `commande` (`ID_Com`),
  ADD CONSTRAINT `ligne_commande_ibfk_2` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`);

--
-- Constraints for table `ligne_panier`
--
ALTER TABLE `ligne_panier`
  ADD CONSTRAINT `ligne_panier_ibfk_1` FOREIGN KEY (`ID_Panier`) REFERENCES `panier` (`ID_Panier`),
  ADD CONSTRAINT `ligne_panier_ibfk_2` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`);

--
-- Constraints for table `notification`
--
ALTER TABLE `notification`
  ADD CONSTRAINT `notification_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`);

--
-- Constraints for table `paiement`
--
ALTER TABLE `paiement`
  ADD CONSTRAINT `paiement_ibfk_1` FOREIGN KEY (`ID_Com`) REFERENCES `commande` (`ID_Com`);

--
-- Constraints for table `panier`
--
ALTER TABLE `panier`
  ADD CONSTRAINT `panier_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`);

--
-- Constraints for table `produit`
--
ALTER TABLE `produit`
  ADD CONSTRAINT `produit_ibfk_1` FOREIGN KEY (`ID_boutique`) REFERENCES `boutique` (`ID_boutique`),
  ADD CONSTRAINT `produit_ibfk_2` FOREIGN KEY (`ID_Categ`) REFERENCES `categorie` (`ID_Categ`);

--
-- Constraints for table `produit_caracteristique`
--
ALTER TABLE `produit_caracteristique`
  ADD CONSTRAINT `produit_caracteristique_ibfk_1` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`) ON DELETE CASCADE;

--
-- Constraints for table `produit_image`
--
ALTER TABLE `produit_image`
  ADD CONSTRAINT `produit_image_ibfk_1` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`) ON DELETE CASCADE;

--
-- Constraints for table `produit_option`
--
ALTER TABLE `produit_option`
  ADD CONSTRAINT `produit_option_ibfk_1` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`) ON DELETE CASCADE;

--
-- Constraints for table `produit_option_valeur`
--
ALTER TABLE `produit_option_valeur`
  ADD CONSTRAINT `produit_option_valeur_ibfk_1` FOREIGN KEY (`ID_Option`) REFERENCES `produit_option` (`ID_Option`) ON DELETE CASCADE;

--
-- Constraints for table `reclamation`
--
ALTER TABLE `reclamation`
  ADD CONSTRAINT `reclamation_ibfk_1` FOREIGN KEY (`ID_Com`) REFERENCES `commande` (`ID_Com`),
  ADD CONSTRAINT `reclamation_ibfk_2` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`);

--
-- Constraints for table `reponse`
--
ALTER TABLE `reponse`
  ADD CONSTRAINT `reponse_ibfk_1` FOREIGN KEY (`ID_utili`) REFERENCES `utilisateur` (`ID_utili`),
  ADD CONSTRAINT `reponse_ibfk_2` FOREIGN KEY (`ID_Avis`) REFERENCES `avis` (`ID_Avis`);

--
-- Constraints for table `traceabilite`
--
ALTER TABLE `traceabilite`
  ADD CONSTRAINT `traceabilite_ibfk_1` FOREIGN KEY (`ID_Prod`) REFERENCES `produit` (`ID_Prod`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
